export const queryKeys = {
  batches: ["batches"] as const,
  batch: (id: string | number) => ["batches", String(id)] as const,
  academic: (params?: unknown) => ["academic-records", params] as const,
  academicDetail: (id: string | number) => ["academic-records", String(id)] as const,
  documents: (params?: unknown) => ["document-submissions", params] as const,
  document: (id: string | number) => ["document-submissions", String(id)] as const,
  documentPackages: (params?: unknown) => ["document-submission-packages", params] as const,
  documentPackage: (granteeId: string | number, batchId: string | number) =>
    ["document-submission-packages", String(granteeId), String(batchId)] as const,
  notifications: ["notifications"] as const,
  grantees: (params?: unknown) => ["grantees", params] as const,
  grantee: (id: string | number) => ["grantees", String(id)] as const,
  eligibility: (params?: unknown) => ["eligibility", params] as const,
  eligibilityDetail: (id: string | number) => ["eligibility", String(id)] as const,
  auditLogs: ["audit-logs"] as const,
  submissionWindow: ["submission-window"] as const,
  faceReviews: ["face-reviews"] as const,
  // Dynamic Forms
  forms: (params?: unknown) => ["forms", params] as const,
  form: (id: string | number) => ["forms", String(id)] as const,
  formResponses: (id: string | number, params?: unknown) => ["forms", String(id), "responses", params] as const,
  formSecurityLogs: (id: string | number, params?: unknown) => ["forms", String(id), "security-logs", params] as const,
  assignedForms: ["forms", "assigned"] as const,
  publicForm: (token: string) => ["forms", "public", token] as const,
  studentAnnouncements: ["student-announcements"] as const,
  studentAnnouncement: (id: string | number) => ["student-announcements", String(id)] as const,
};
