<script setup lang="ts">
import { computed, ref } from "vue";
import { useRoute } from "vue-router";
import { useQuery, useQueryClient } from "@tanstack/vue-query";
import { IconArrowLeft, IconLoader, IconSend } from "@tabler/icons-vue";
import { apiFetch } from "@/api/client";
import DiceBearAvatar from "@/components/ui/DiceBearAvatar.vue";
import { toast } from "@/composables/useToast";
type Ticket = { id: number; ticket_id: string; title: string; category: string; priority: string; status: string; description?: string | null; created_at: string; reporter: string; assignee: string; replies: { author: string; message: string; created_at: string }[] };
const route = useRoute(); const queryClient = useQueryClient(); const id = computed(() => Number(route.params.id)); const reply = ref(""); const saving = ref(false);
const ticketQuery = useQuery({ queryKey: ["support-tickets"], queryFn: () => apiFetch<{ data: Ticket[] }>("/api/support-tickets") });
const ticket = computed(() => ticketQuery.data.value?.data.find((item) => item.id === id.value) ?? null);
async function update(payload: Record<string, string>) { if (!ticket.value) return; saving.value = true; try { await apiFetch(`/api/support-tickets/${ticket.value.id}`, { method: "PATCH", body: JSON.stringify(payload) }); await queryClient.invalidateQueries({ queryKey: ["support-tickets"] }); reply.value = ""; toast.success("Ticket updated."); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to update ticket."); } finally { saving.value = false; } }
function updateStatus(event: Event) { update({ status: (event.target as HTMLSelectElement).value }); }
</script>
<template><div><RouterLink to="/app/support" class="mb-3 inline-flex items-center gap-1 text-xs text-text-muted hover:text-primary"><IconArrowLeft :size="14" />Back to inbox</RouterLink><div v-if="ticketQuery.isLoading.value" class="grid min-h-48 place-items-center rounded-xl border bg-surface text-sm text-text-muted"><IconLoader :size="18" class="mr-2 animate-spin" />Loading ticket…</div><div v-else-if="ticketQuery.isError.value || !ticket" class="rounded-xl border border-danger bg-surface p-6 text-sm text-danger">Ticket not found or unavailable.</div><section v-else class="mx-auto max-w-4xl overflow-hidden rounded-xl border bg-surface"><header class="flex flex-wrap items-start justify-between gap-3 border-b p-5"><div><h1 class="text-xl font-semibold">{{ ticket.title }}</h1><p class="mt-1 text-xs text-text-muted">{{ ticket.ticket_id }} · {{ ticket.category }} · {{ ticket.priority }} priority</p></div><select :value="ticket.status" :disabled="saving" class="h-9 rounded-md border bg-surface px-3 text-xs" @change="updateStatus"><option>Open</option><option>In Progress</option><option>Waiting</option><option>Resolved</option></select></header><div class="min-h-80 space-y-6 p-5"><article class="flex gap-3"><DiceBearAvatar :seed="ticket.reporter" :alt="ticket.reporter" :size="36" /><div><p class="text-sm font-semibold">{{ ticket.reporter }}</p><p class="mt-2 rounded-lg rounded-tl-none border p-4 text-sm text-text-muted">{{ ticket.description || 'No description was provided.' }}</p></div></article><article v-for="(message, index) in ticket.replies" :key="index" class="flex gap-3"><DiceBearAvatar :seed="message.author" :alt="message.author" :size="36" /><div><p class="text-sm font-semibold">{{ message.author }}</p><p class="mt-2 rounded-lg rounded-tl-none border p-4 text-sm text-text-muted">{{ message.message }}</p></div></article></div><form class="border-t bg-surface-muted/30 p-5" @submit.prevent="reply.trim() && update({ reply: reply.trim() })"><textarea v-model="reply" class="min-h-28 w-full resize-none rounded-md border bg-surface p-3 text-sm" placeholder="Reply to this conversation…" /><div class="mt-2 flex justify-end"><button :disabled="saving || !reply.trim()" class="inline-flex items-center gap-1.5 rounded-md bg-primary px-4 py-2 text-xs text-white disabled:opacity-50"><IconSend :size="14" />{{ saving ? 'Sending…' : 'Send reply' }}</button></div></form></section></div></template>
