<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Distribution Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #111; margin: 28px; }
        h1 { font-size: 16px; margin: 0 0 4px; text-align: center; }
        h2 { font-size: 13px; margin: 0 0 16px; text-align: center; font-weight: normal; }
        .meta { margin-bottom: 16px; }
        .meta td { padding: 2px 8px 2px 0; vertical-align: top; }
        .meta .label { color: #555; width: 140px; }
        table.grid { width: 100%; border-collapse: collapse; margin-top: 8px; }
        table.grid th, table.grid td { border: 1px solid #333; padding: 5px 6px; }
        table.grid th { background: #f0f0f0; text-align: left; font-size: 10px; text-transform: uppercase; }
        .right { text-align: right; }
        .center { text-align: center; }
        .section { margin-top: 18px; font-size: 12px; font-weight: bold; }
        .totals { margin-top: 14px; width: 100%; }
        .totals td { padding: 3px 0; }
        .footer { margin-top: 28px; font-size: 9px; color: #555; border-top: 1px solid #ccc; padding-top: 8px; }
        .badge { font-size: 9px; letter-spacing: 0.04em; text-transform: uppercase; }
        .summary { width: 100%; margin-bottom: 12px; border-collapse: collapse; }
        .summary td { border: 1px solid #333; padding: 8px; width: 33%; }
        .summary .k { font-size: 9px; color: #555; text-transform: uppercase; }
        .summary .v { font-size: 14px; font-weight: bold; margin-top: 2px; }
    </style>
</head>
<body>
    <p class="badge center">Commission on Higher Education · UniFAST · Tertiary Education Subsidy</p>
    <h1>Distribution Report</h1>
    <h2>Auditable stipend release summary · PHP {{ number_format((float) $report->stipend_per_grantee, 2) }} per verified grantee</h2>

    <table class="meta">
        <tr>
            <td class="label">Batch</td>
            <td><strong>{{ $batch->name }}</strong></td>
            <td class="label">Academic Year</td>
            <td>{{ $batch->academic_year }}</td>
        </tr>
        <tr>
            <td class="label">Semester</td>
            <td>{{ $batch->semester }}</td>
            <td class="label">Generated</td>
            <td>{{ optional($generatedAt)->format('Y-m-d H:i') }}</td>
        </tr>
        <tr>
            <td class="label">Generated by</td>
            <td>{{ $generatedBy }}</td>
            <td class="label">Report ID</td>
            <td>#{{ $report->id }}</td>
        </tr>
    </table>

    <table class="summary">
        <tr>
            <td>
                <div class="k">Total verified grantees</div>
                <div class="v">{{ $report->total_grantees }}</div>
            </td>
            <td>
                <div class="k">Total stipend released</div>
                <div class="v">PHP {{ number_format((float) $report->total_amount, 2) }}</div>
            </td>
            <td>
                <div class="k">Excluded grantees</div>
                <div class="v">{{ $excludedItems->count() }}</div>
            </td>
        </tr>
    </table>

    <div class="section">Per-grantee status — included (verified)</div>
    <table class="grid">
        <thead>
            <tr>
                <th style="width: 28px;">#</th>
                <th>Full Name</th>
                <th>Student ID</th>
                <th>Program</th>
                <th>Status</th>
                <th class="right">Stipend (PHP)</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($includedItems as $index => $item)
                <tr>
                    <td class="center">{{ $index + 1 }}</td>
                    <td>{{ $item->full_name }}</td>
                    <td>{{ $item->student_id }}</td>
                    <td>{{ $item->program }}</td>
                    <td>Verified / Released</td>
                    <td class="right">{{ number_format((float) $item->stipend_amount, 2) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" class="center">No verified grantees for distribution.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="section">Excluded grantees (with reasons)</div>
    <table class="grid">
        <thead>
            <tr>
                <th style="width: 28px;">#</th>
                <th>Full Name</th>
                <th>Student ID</th>
                <th>Program</th>
                <th>Status</th>
                <th>Exclusion reason</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($excludedItems as $index => $item)
                <tr>
                    <td class="center">{{ $index + 1 }}</td>
                    <td>{{ $item->full_name }}</td>
                    <td>{{ $item->student_id }}</td>
                    <td>{{ $item->program }}</td>
                    <td>Excluded</td>
                    <td>{{ $item->exclusion_reason }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" class="center">No excluded grantees.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <table class="totals">
        <tr>
            <td><strong>Total verified grantees</strong></td>
            <td class="right"><strong>{{ $report->total_grantees }}</strong></td>
        </tr>
        <tr>
            <td><strong>Total stipend released</strong></td>
            <td class="right"><strong>PHP {{ number_format((float) $report->total_amount, 2) }}</strong></td>
        </tr>
    </table>

    <div class="footer">
        CHED / UniFAST TES distribution summary for audit. Generated after the distribution period for batch {{ $batch->name }}.
        Report #{{ $report->id }} · Stipend rate PHP {{ number_format((float) $report->stipend_per_grantee, 2) }} per semester.
    </div>
</body>
</html>
