/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppMasterlistRouteImport } from './routes/app.masterlist'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthLockedRouteImport } from './routes/_auth.locked'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthActivateSuccessRouteImport } from './routes/_auth.activate-success'
import { Route as AuthActivateRouteImport } from './routes/_auth.activate'
import { Route as AppGranteesIndexRouteImport } from './routes/app.grantees.index'
import { Route as AppEligibilityIndexRouteImport } from './routes/app.eligibility.index'
import { Route as AppDocumentsIndexRouteImport } from './routes/app.documents.index'
import { Route as AppBatchesIndexRouteImport } from './routes/app.batches.index'
import { Route as AppAcademicIndexRouteImport } from './routes/app.academic.index'
import { Route as AppGranteesIdRouteImport } from './routes/app.grantees.$id'
import { Route as AppEligibilityIdRouteImport } from './routes/app.eligibility.$id'
import { Route as AppDocumentsIdRouteImport } from './routes/app.documents.$id'
import { Route as AppBatchesIdRouteImport } from './routes/app.batches.$id'
import { Route as AppAcademicIdRouteImport } from './routes/app.academic.$id'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterlistRoute = AppMasterlistRouteImport.update({
  id: '/masterlist',
  path: '/masterlist',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLockedRoute = AuthLockedRouteImport.update({
  id: '/locked',
  path: '/locked',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthActivateSuccessRoute = AuthActivateSuccessRouteImport.update({
  id: '/activate-success',
  path: '/activate-success',
  getParentRoute: () => AuthRoute,
} as any)
const AuthActivateRoute = AuthActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => AuthRoute,
} as any)
const AppGranteesIndexRoute = AppGranteesIndexRouteImport.update({
  id: '/grantees/',
  path: '/grantees/',
  getParentRoute: () => AppRoute,
} as any)
const AppEligibilityIndexRoute = AppEligibilityIndexRouteImport.update({
  id: '/eligibility/',
  path: '/eligibility/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesIndexRoute = AppBatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicIndexRoute = AppAcademicIndexRouteImport.update({
  id: '/academic/',
  path: '/academic/',
  getParentRoute: () => AppRoute,
} as any)
const AppGranteesIdRoute = AppGranteesIdRouteImport.update({
  id: '/grantees/$id',
  path: '/grantees/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEligibilityIdRoute = AppEligibilityIdRouteImport.update({
  id: '/eligibility/$id',
  path: '/eligibility/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIdRoute = AppDocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesIdRoute = AppBatchesIdRouteImport.update({
  id: '/batches/$id',
  path: '/batches/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicIdRoute = AppAcademicIdRouteImport.update({
  id: '/academic/$id',
  path: '/academic/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/student': typeof StudentRoute
  '/activate': typeof AuthActivateRoute
  '/activate-success': typeof AuthActivateSuccessRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/locked': typeof AuthLockedRoute
  '/login': typeof AuthLoginRoute
  '/app/masterlist': typeof AppMasterlistRoute
  '/app/': typeof AppIndexRoute
  '/app/academic/$id': typeof AppAcademicIdRoute
  '/app/batches/$id': typeof AppBatchesIdRoute
  '/app/documents/$id': typeof AppDocumentsIdRoute
  '/app/eligibility/$id': typeof AppEligibilityIdRoute
  '/app/grantees/$id': typeof AppGranteesIdRoute
  '/app/academic/': typeof AppAcademicIndexRoute
  '/app/batches/': typeof AppBatchesIndexRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/eligibility/': typeof AppEligibilityIndexRoute
  '/app/grantees/': typeof AppGranteesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/student': typeof StudentRoute
  '/activate': typeof AuthActivateRoute
  '/activate-success': typeof AuthActivateSuccessRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/locked': typeof AuthLockedRoute
  '/login': typeof AuthLoginRoute
  '/app/masterlist': typeof AppMasterlistRoute
  '/app': typeof AppIndexRoute
  '/app/academic/$id': typeof AppAcademicIdRoute
  '/app/batches/$id': typeof AppBatchesIdRoute
  '/app/documents/$id': typeof AppDocumentsIdRoute
  '/app/eligibility/$id': typeof AppEligibilityIdRoute
  '/app/grantees/$id': typeof AppGranteesIdRoute
  '/app/academic': typeof AppAcademicIndexRoute
  '/app/batches': typeof AppBatchesIndexRoute
  '/app/documents': typeof AppDocumentsIndexRoute
  '/app/eligibility': typeof AppEligibilityIndexRoute
  '/app/grantees': typeof AppGranteesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/student': typeof StudentRoute
  '/_auth/activate': typeof AuthActivateRoute
  '/_auth/activate-success': typeof AuthActivateSuccessRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/locked': typeof AuthLockedRoute
  '/_auth/login': typeof AuthLoginRoute
  '/app/masterlist': typeof AppMasterlistRoute
  '/app/': typeof AppIndexRoute
  '/app/academic/$id': typeof AppAcademicIdRoute
  '/app/batches/$id': typeof AppBatchesIdRoute
  '/app/documents/$id': typeof AppDocumentsIdRoute
  '/app/eligibility/$id': typeof AppEligibilityIdRoute
  '/app/grantees/$id': typeof AppGranteesIdRoute
  '/app/academic/': typeof AppAcademicIndexRoute
  '/app/batches/': typeof AppBatchesIndexRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/eligibility/': typeof AppEligibilityIndexRoute
  '/app/grantees/': typeof AppGranteesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/student'
    | '/activate'
    | '/activate-success'
    | '/forgot-password'
    | '/locked'
    | '/login'
    | '/app/masterlist'
    | '/app/'
    | '/app/academic/$id'
    | '/app/batches/$id'
    | '/app/documents/$id'
    | '/app/eligibility/$id'
    | '/app/grantees/$id'
    | '/app/academic/'
    | '/app/batches/'
    | '/app/documents/'
    | '/app/eligibility/'
    | '/app/grantees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/student'
    | '/activate'
    | '/activate-success'
    | '/forgot-password'
    | '/locked'
    | '/login'
    | '/app/masterlist'
    | '/app'
    | '/app/academic/$id'
    | '/app/batches/$id'
    | '/app/documents/$id'
    | '/app/eligibility/$id'
    | '/app/grantees/$id'
    | '/app/academic'
    | '/app/batches'
    | '/app/documents'
    | '/app/eligibility'
    | '/app/grantees'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app'
    | '/student'
    | '/_auth/activate'
    | '/_auth/activate-success'
    | '/_auth/forgot-password'
    | '/_auth/locked'
    | '/_auth/login'
    | '/app/masterlist'
    | '/app/'
    | '/app/academic/$id'
    | '/app/batches/$id'
    | '/app/documents/$id'
    | '/app/eligibility/$id'
    | '/app/grantees/$id'
    | '/app/academic/'
    | '/app/batches/'
    | '/app/documents/'
    | '/app/eligibility/'
    | '/app/grantees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  StudentRoute: typeof StudentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/masterlist': {
      id: '/app/masterlist'
      path: '/masterlist'
      fullPath: '/app/masterlist'
      preLoaderRoute: typeof AppMasterlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/locked': {
      id: '/_auth/locked'
      path: '/locked'
      fullPath: '/locked'
      preLoaderRoute: typeof AuthLockedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/activate-success': {
      id: '/_auth/activate-success'
      path: '/activate-success'
      fullPath: '/activate-success'
      preLoaderRoute: typeof AuthActivateSuccessRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/activate': {
      id: '/_auth/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof AuthActivateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/grantees/': {
      id: '/app/grantees/'
      path: '/grantees'
      fullPath: '/app/grantees/'
      preLoaderRoute: typeof AppGranteesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/eligibility/': {
      id: '/app/eligibility/'
      path: '/eligibility'
      fullPath: '/app/eligibility/'
      preLoaderRoute: typeof AppEligibilityIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/': {
      id: '/app/documents/'
      path: '/documents'
      fullPath: '/app/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batches/': {
      id: '/app/batches/'
      path: '/batches'
      fullPath: '/app/batches/'
      preLoaderRoute: typeof AppBatchesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/academic/': {
      id: '/app/academic/'
      path: '/academic'
      fullPath: '/app/academic/'
      preLoaderRoute: typeof AppAcademicIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grantees/$id': {
      id: '/app/grantees/$id'
      path: '/grantees/$id'
      fullPath: '/app/grantees/$id'
      preLoaderRoute: typeof AppGranteesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/eligibility/$id': {
      id: '/app/eligibility/$id'
      path: '/eligibility/$id'
      fullPath: '/app/eligibility/$id'
      preLoaderRoute: typeof AppEligibilityIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/$id': {
      id: '/app/documents/$id'
      path: '/documents/$id'
      fullPath: '/app/documents/$id'
      preLoaderRoute: typeof AppDocumentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batches/$id': {
      id: '/app/batches/$id'
      path: '/batches/$id'
      fullPath: '/app/batches/$id'
      preLoaderRoute: typeof AppBatchesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/academic/$id': {
      id: '/app/academic/$id'
      path: '/academic/$id'
      fullPath: '/app/academic/$id'
      preLoaderRoute: typeof AppAcademicIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AuthRouteChildren {
  AuthActivateRoute: typeof AuthActivateRoute
  AuthActivateSuccessRoute: typeof AuthActivateSuccessRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLockedRoute: typeof AuthLockedRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthActivateRoute: AuthActivateRoute,
  AuthActivateSuccessRoute: AuthActivateSuccessRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLockedRoute: AuthLockedRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AppRouteChildren {
  AppMasterlistRoute: typeof AppMasterlistRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAcademicIdRoute: typeof AppAcademicIdRoute
  AppBatchesIdRoute: typeof AppBatchesIdRoute
  AppDocumentsIdRoute: typeof AppDocumentsIdRoute
  AppEligibilityIdRoute: typeof AppEligibilityIdRoute
  AppGranteesIdRoute: typeof AppGranteesIdRoute
  AppAcademicIndexRoute: typeof AppAcademicIndexRoute
  AppBatchesIndexRoute: typeof AppBatchesIndexRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppEligibilityIndexRoute: typeof AppEligibilityIndexRoute
  AppGranteesIndexRoute: typeof AppGranteesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMasterlistRoute: AppMasterlistRoute,
  AppIndexRoute: AppIndexRoute,
  AppAcademicIdRoute: AppAcademicIdRoute,
  AppBatchesIdRoute: AppBatchesIdRoute,
  AppDocumentsIdRoute: AppDocumentsIdRoute,
  AppEligibilityIdRoute: AppEligibilityIdRoute,
  AppGranteesIdRoute: AppGranteesIdRoute,
  AppAcademicIndexRoute: AppAcademicIndexRoute,
  AppBatchesIndexRoute: AppBatchesIndexRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppEligibilityIndexRoute: AppEligibilityIndexRoute,
  AppGranteesIndexRoute: AppGranteesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  StudentRoute: StudentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
